### ISSUE TITLE
Rückfrage zu dem Thema "Punktesystem" in "Informationen zum Ingamesupport

### ISSUE THREAD

**Issue by Ru8ior** [FLBadoras/wiki#108]
Related zu support.md

Ich habe keine Ahnung, wie ich dort irgendwelche Kommentare oder Vorschläge machen kann, deswegen erstelle ich jetzt einfach ganz clean nh neue issue. 

Was hat es mit diesem Punkt auf sich? 
![image](https://github.com/FLBadoras/wiki/assets/165582373/22bb0e96-2780-4953-8927-b1e53237de4c)

Was willst du hier denn noch ergänzen @motrellin?

**Comment by motrellin** [comment]
> Related zu support.md
> 
> Ich habe keine Ahnung, wie ich dort irgendwelche Kommentare oder Vorschläge machen kann, deswegen erstelle ich jetzt einfach ganz clean nh neue issue.

Kann man nicht direkt, aber es hätte schon #106 gegeben, dort kann man ja kommentieren.

> Was hat es mit diesem Punkt auf sich? ![image](https://private-user-images.githubusercontent.com/165582373/324181404-22bb0e96-2780-4953-8927-b1e53237de4c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM2MjgxMDYsIm5iZiI6MTcxMzYyNzgwNiwicGF0aCI6Ii8xNjU1ODIzNzMvMzI0MTgxNDA0LTIyYmIwZTk2LTI3ODAtNDk1My04OTI3LWIxZTUzMjM3ZGU0Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyMFQxNTQzMjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ODcyNTcxNGNhODcyODZhNDBlNGViN2QyMzY1NDBlN2ViZTZiZmJkYTA4YWMwMTJiYWM5YTVlZDRkMjA1MWQ2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.X1QYmA6jfaMNSkck5NeaiMvvm-JRbsoZ9gMEunQSUk8)
> 
> Was willst du hier denn noch ergänzen @motrellin?

Naja, die Informationen über das Punktesystem, die die Spieler bekommen. Auf dem TimberLife-Server wäre das beispielsweise gewesen, dass man nach Erreichen von 100 Punkten des Servers verwiesen wird und dass man Punkte bekommt, wenn man Regelverstöße begeht. Ohne Garantie auf Vollständigkeit. Long story short: Die Informationen zu dem Punktesystem, die public an die Spieler gehen können.
