### ISSUE TITLE
[SYS] Shops

### ISSUE THREAD

**Issue by motrellin** [FLBadoras/wiki#115]
### System

Shops

### Überblick

Unsere Spieler*innen können sich Shops mieten und diese mit einzelnen Kisten-Shops einrichten.

### Beschreibung und wichtige Details

Shops sind erstmal Grundstücke, die gemietet (nicht gekauft) werden können. Innerhalb dieser Shops können Kisten-Shops eingerichtet werden. Diese sind vielseitig einrichtbar. 

Mehr Infos folgen.

### Zugehörige Commands

Der Haupt-Command ist `/shop`, der jedoch mehrere Unter-Commands hat. Wir müssen noch durchgehen, welche erwähnenswert sind.

### Überprüfung

- [X] Alle benötigten Informationen (vgl. ausgefüllte Informationen zuvor) liegen vor.
- [X] Das System wird noch nicht im Wiki aufgeführt.
- [X] Ich habe auch überprüft, dass das System nicht bereits über eine andere Issue oder Pull Request hinzugefügt wird.

**Comment by RobZenFL** [comment]
Done. Folgt mit der nächsten PR.
