### ISSUE TITLE
[COMMAND] /me

### ISSUE THREAD

**Issue by motrellin** [FLBadoras/wiki#14]
### Command

/me

### Beispiel

/me zeigt auf Peter.

### Beschreibung

Chatbefehl - Kürzel für den Emotechat. Der Emotechat kann für Roleplay genutzt werden und nur Spieler im Umkreis von 30 Metern können die Nachricht lesen. Der Emotechat beschreibt nicht darstellbare Handlungen deines Charakters, wie beispielsweise "winken" oder "zeigen".

Nutzung:

Einfach /me tippen: Aktiviert den Emotekanal dauerhaft und alles, was man in den Chat tippt, landet in diesem Kanal.
/me [Nachricht]: Wenn man zum Beispiel den Lokalchat aktiviert hat, kann man mit "/me [Nachricht]" einmalig in den Emotekanal schreiben, danach schreibt man automatisch im Lokalchat weiter.

Übersicht über alle Chatkanäle: /chat

### Aliase

Keine Aliase bekannt.

### Überprüfung

- [X] Alle benötigten Informationen (vgl. ausgefüllte Informationen zuvor) liegen vor.
- [X] Der Command wird noch nicht im Wiki aufgeführt.
- [X] Ich habe auch überprüft, dass der Command nicht bereits über eine andere Pull Request hinzugefügt wird.

**Comment by motrellin** [comment]
@RobZenFL FYI: Nur `/me` togglet den Chat nicht.

**Comment by RobZenFL** [comment]
Gefixt
