### ISSUE TITLE
[IMPROVEMENT] /ehepaare Alias ergänzen

### ISSUE THREAD

**Issue by RobZenFL** [FLBadoras/wiki#143]
### Grobbeschreibung

Bei /ehepaare bitte den Alias /marry list ergänzen.

**Comment by motrellin** [comment]
Eventuell lieber anders herum, also `/ehepaare` als Alias? Stimmt dann mehr mit den aliaslosen Commands überein.

**Comment by RobZenFL** [comment]
Done. Kommt mit der nächsten PR.
