### ISSUE TITLE
[COMMAND] /einsatz

### ISSUE THREAD

**Issue by motrellin** [FLBadoras/wiki#16]
### Command

/einsatz

/einsatz {Betrag}

Verwendung unbekannt.

### Beschreibung

Command für den Boxring. Du kannst hiermit deinen Einsatz für einen Boxkampf festlegen. Der Gegner erhält diesen Betrag, sollte er gewinnen. Gewinnst du, erhältst du den Betrag, den der Gegner vorher mit diesem Befehl festgelegt hat. Nach jedem Boxkampf wird der Betrag auf 0 Euro zurückgesetzt.

### Aliase

Keine Aliase bekannt.

### Überprüfung

- [X] Alle benötigten Informationen (vgl. ausgefüllte Informationen zuvor) liegen vor.
- [X] Der Command wird noch nicht im Wiki aufgeführt.
- [X] Ich habe auch überprüft, dass der Command nicht bereits über eine andere Pull Request hinzugefügt wird.

**Comment by RobZenFL** [comment]
Done. Kommt in der nächsten PR.
