### ISSUE TITLE
Getränke-Mechanik hat sich geändert

### ISSUE THREAD

**Issue by RobZenFL** [FLBadoras/wiki#164]
https://github.com/FLBadoras/wiki/blob/2fce462d2010482bf73a32ad6af68933d96e12dd/_systems/fooddrinks.md?plain=1#L39

Muss angepasst werden.

Neue Mechanik:
Rezepte erhält man wie gehabt bei der Küchenhilfe. Die gelernten Rezepte kann man dann beim Apfelfeld an der Getränkemaschine herstellen. Man muss den Wassertank der Maschine füllen und die Zutaten bei sich haben, um eine Produktion starten zu können.

**Comment by motrellin** [comment]
@RobZenFL Ist das jetzt eine zusätzliche Möglichkeit oder die einzige, die jetzt noch möglich ist?
