### ISSUE TITLE
[COMMAND] /nachrichten

### ISSUE THREAD

**Issue by motrellin** [FLBadoras/wiki#18]
### Command

/nachrichten

### Beispiel

/nachrichten {Nummer}
/nachrichten {löschen}

### Beschreibung

Wenn du Offline-Privatnachrichten erhalten hast, kannst du sie mit diesem Befehl nachlesen oder löschen.

### Aliase

Keine Aliase bekannt.

### Überprüfung

- [X] Alle benötigten Informationen (vgl. ausgefüllte Informationen zuvor) liegen vor.
- [X] Der Command wird noch nicht im Wiki aufgeführt.
- [X] Ich habe auch überprüft, dass der Command nicht bereits über eine andere Pull Request hinzugefügt wird.

**Comment by RobZenFL** [comment]
Done. Folgt in der nächsten PR.
