### ISSUE TITLE
[COMMAND] /ev

### ISSUE THREAD

**Issue by motrellin** [FLBadoras/wiki#24]
### Command

/ev

### Beispiel

/ev [Nachricht]

### Beschreibung

Ohne Nachricht wechselt man dauerhaft in den Eventchat. Mit Nachricht schreibt man einmalig eine Nachricht im Eventchat.

### Aliase

Keine Aliase bekannt.

### Überprüfung

- [X] Alle benötigten Informationen (vgl. ausgefüllte Informationen zuvor) liegen vor.
- [X] Der Command wird noch nicht im Wiki aufgeführt.
- [X] Ich habe auch überprüft, dass der Command nicht bereits über eine andere Pull Request hinzugefügt wird.

**Comment by RobZenFL** [comment]
Chatbefehl - Kürzel für den Eventchat.

Nutzung: 
- Einfach /ev tippen: aktiviert den Eventkanal dauerhaft und alles was man in den Chat tippt, landet dort.
- /ev [Nachricht]: Wenn man zum Beispiel den Globalchat aktiviert hat, kann man mit /ev [Nachricht] einmalig in den Eventkanal schreiben, danach schreibt man automatisch im Globalchat weiter.
