### ISSUE TITLE
[COMMAND] /merch

### ISSUE THREAD

**Issue by motrellin** [FLBadoras/wiki#26]
### Command

/merch

### Beispiel

/merch

### Beschreibung

Link zum FarmLife-Merchshop

### Aliase

Keine Aliase bekannt.

### Überprüfung

- [X] Alle benötigten Informationen (vgl. ausgefüllte Informationen zuvor) liegen vor.
- [X] Der Command wird noch nicht im Wiki aufgeführt.
- [X] Ich habe auch überprüft, dass der Command nicht bereits über eine andere Pull Request hinzugefügt wird.

**Comment by RobZenFL** [comment]
Link zum FarmLife-Merchshop

**Comment by motrellin** [comment]
Info nicht mehr aktuell, der hier beschriebene Befehl ist eigentlich `/merch`. Ich ändere das ab.
