### ISSUE TITLE
[COMMAND] /gps

### ISSUE THREAD

**Issue by motrellin** [FLBadoras/wiki#27]
### Command

/gps

### Beispiel

Verwendung unbekannt.

### Beschreibung

Details unbekannt.

### Aliase

Keine Aliase bekannt.

### Überprüfung

- [ ] Alle benötigten Informationen (vgl. ausgefüllte Informationen zuvor) liegen vor.
- [X] Der Command wird noch nicht im Wiki aufgeführt.
- [X] Ich habe auch überprüft, dass der Command nicht bereits über eine andere Pull Request hinzugefügt wird.

**Comment by motrellin** [comment]
@RobZenFL ist das einfach nur ein Alias für /navi ?

**Comment by RobZenFL** [comment]
Korrekt
