### ISSUE TITLE
[COMMAND] /skills

### ISSUE THREAD

**Issue by motrellin** [FLBadoras/wiki#28]
### Command

/skills

### Beispiel

Verwendung unbekannt.

### Beschreibung

Details unbekannt.

### Aliase

Keine Aliase bekannt.

### Überprüfung

- [ ] Alle benötigten Informationen (vgl. ausgefüllte Informationen zuvor) liegen vor.
- [X] Der Command wird noch nicht im Wiki aufgeführt.
- [X] Ich habe auch überprüft, dass der Command nicht bereits über eine andere Pull Request hinzugefügt wird.

**Comment by RobZenFL** [comment]
Übersicht über alle Skills, deren Fortschritte und Inhalte
