### ISSUE TITLE
[COMMAND] /akrobatik

### ISSUE THREAD

**Issue by motrellin** [FLBadoras/wiki#29]
### Command

/akrobatik

### Beispiel

/akrobatik

### Beschreibung

McMMO-Command - Übersicht über den Skill "Akrobatik"

### Aliase

Keine Aliase bekannt.

### Überprüfung

- [X] Alle benötigten Informationen (vgl. ausgefüllte Informationen zuvor) liegen vor.
- [X] Der Command wird noch nicht im Wiki aufgeführt.
- [X] Ich habe auch überprüft, dass der Command nicht bereits über eine andere Pull Request hinzugefügt wird.

**Comment by RobZenFL** [comment]
McMMO-Command - Übersicht über den Skill "Akrobatik"

Übersicht über alle findet man unter /skills
