### ISSUE TITLE
[COMMAND] /kräuterkunde

### ISSUE THREAD

**Issue by motrellin** [FLBadoras/wiki#38]
### Command

/kräuterkunde

### Beispiel

Verwendung unbekannt.

### Beschreibung

Details unbekannt.

### Aliase

Keine Aliase bekannt.

### Überprüfung

- [x] Alle benötigten Informationen (vgl. ausgefüllte Informationen zuvor) liegen vor.
- [X] Der Command wird noch nicht im Wiki aufgeführt.
- [X] Ich habe auch überprüft, dass der Command nicht bereits über eine andere Pull Request hinzugefügt wird.

**Comment by RobZenFL** [comment]
McMMO-Command - Übersicht über den Skill "Kräuterkunde"
