### ISSUE TITLE
[COMMAND] /webseite

### ISSUE THREAD

**Issue by motrellin** [FLBadoras/wiki#42]
### Command

/webseite

### Beispiel

/webseite

### Beschreibung

Gibt den Link zur Website aus.

### Aliase

/homepage

### Überprüfung

- [X] Alle benötigten Informationen (vgl. ausgefüllte Informationen zuvor) liegen vor.
- [X] Der Command wird noch nicht im Wiki aufgeführt.
- [X] Ich habe auch überprüft, dass der Command nicht bereits über eine andere Pull Request hinzugefügt wird.

**Comment by motrellin** [comment]
@RobZenFL Bitte nochmal überprüfen, insbesondere ob /homepage und /website wirklich Aliase sind.

**Comment by RobZenFL** [comment]
Aliase:
- webseite
- website
- homepage

**Comment by motrellin** [comment]
default: website
rest wird zu aliasen
