### ISSUE TITLE
[COMMAND] /gemälde

### ISSUE THREAD

**Issue by motrellin** [FLBadoras/wiki#46]
### Command

/gemälde

### Beispiel

Verwendung unbekannt.

### Beschreibung

Details unbekannt.

### Aliase

Keine Aliase bekannt.

### Überprüfung

- [x] Alle benötigten Informationen (vgl. ausgefüllte Informationen zuvor) liegen vor.
- [X] Der Command wird noch nicht im Wiki aufgeführt.
- [X] Ich habe auch überprüft, dass der Command nicht bereits über eine andere Pull Request hinzugefügt wird.

**Comment by RobZenFL** [comment]
Der Command wird genutzt, um ein gemaltes Bild an der Staffelei abzuspeichern. Mit /gemälde [NAME] speicherst du es ab und kannst es fortan verwenden.

**Comment by motrellin** [comment]
Kann man dann schätzungsweise dem System "drawing" zuordnen.

**Comment by RobZenFL** [comment]
Done. Folgt in der nächsten PR.
