### ISSUE TITLE
[COMMAND] /e

### ISSUE THREAD

**Issue by motrellin** [FLBadoras/wiki#47]
### Command

/e

### Beispiel

Verwendung unbekannt.

### Beschreibung

Details unbekannt.

### Aliase

Keine Aliase bekannt.

### Überprüfung

- [x] Alle benötigten Informationen (vgl. ausgefüllte Informationen zuvor) liegen vor.
- [X] Der Command wird noch nicht im Wiki aufgeführt.
- [X] Ich habe auch überprüft, dass der Command nicht bereits über eine andere Pull Request hinzugefügt wird.

**Comment by RobZenFL** [comment]
/e wird genutzt, um die verfügbaren Emojis im Chat anzuzeigen. Wenn du nur /e machst, öffnet sich die Übersicht. Wenn du "/e Hallo smile" machst, schlägt er dir anhand der eingetippten Wärter (hier "smile") passende Emojios vor, die du dann übernehmen kannst. So muss man sich nicht alle Emojinamen merken (wenn du :smile: tippst, kommt derselbe Emoji).
