### ISSUE TITLE
[COMMAND] grundstück erlauben

### ISSUE THREAD

**Issue by RobZenFL** [FLBadoras/wiki#60]
### Command

/grundstück erlauben {Name}

### Beschreibung

Erteile anderen Spielern Baurechte auf das Grundstück oder den Shop, auf/in dem du gerade stehst.

### Aliase

- /grundstücke erlauben
- /gs erlauben

### Zugehöriges System

Grundstücke

### Überprüfung

- [X] Alle benötigten Informationen (vgl. ausgefüllte Informationen zuvor) liegen vor.
- [X] Der Command wird noch nicht im Wiki aufgeführt.
- [X] Ich habe auch überprüft, dass der Command nicht bereits über eine andere Pull Request hinzugefügt wird.

**Comment by motrellin** [comment]
Ich vermute mal, dass Name ein obligatorisches Argument ist.

**Comment by RobZenFL** [comment]
Korrekt
