### ISSUE TITLE
Add Social Preview

### ISSUE THREAD

**Issue by motrellin** [FLBadoras/wiki#75]
We should add an social preview for the wiki. This can be done under [Settings](https://github.com/FLBadoras/wiki/settings) > Social Preview.

> Images should be at least 640×320px (1280×640px for best display).

**Comment by RobZenFL** [comment]
Glaube done. Weiß nur nicht wie gut da aussieht :D

**Comment by motrellin** [comment]
> Glaube done. Weiß nur nicht wie gut da aussieht :D

Du kannst einfach mal den Link zum Repo (?), evtl auch der Wiki-Link direkt, wem auf Discord schicken, da müsste es sichtbar werden.

**Comment by RobZenFL** [comment]
Done
