### ISSUE TITLE
[IMPROVEMENT] Add command list

### ISSUE THREAD

**Issue by RobZenFL** [FLBadoras/wiki#8]
### Grobbeschreibung

Füge alle Ingame-Commands ein

### Beschreibung

Füge alle Ingame-Commands ein und sei froh, dass sie dann hier sind.

**Comment by motrellin** [comment]
Ich bin aktuell dabei, die Commands von der Website zu übertragen. Wenn das erledigt ist, würde ich die Issue hier schließen, da sie doch sehr unkonkret ist. Ich denke, die Liste muss einfach Stück für Stück erweitert werden, oder @RobZenFL ?

**Comment by RobZenFL** [comment]
**Im Chat sichbare Commands für Spieler**

- Denke Pet-Commands und die Skill-Commands (/holzfällen etc) braucht man evtl nicht extra zu notieren, weil die eingebettet sind in die GUIs etc.

  spieler:
  - /hilfe
  - /me
  - /willkommen
  - /laufen
  - /gehen
  - /schleichen
  - /sitzen
  - /liegen
  - /kriechen
  - /hinwerfen
  - /drehen
  - /uhrzeit
  - /ontime
  - /chat
  - /ehepaare
  - /sichern
  - /entsichern
  - /konto
  - /geld
  - /überweisen
  - /farmgames
  - /einsatz
  - /paket
  - /zurück
  - /nachrichten
  - /plantage
  - /grundstück
  - /gs
  - /g
  - /l
  - /h
  - /a
  - /ev
  - /marry
  - /petcall
  - /petsendaway
  - /petinfo
  - /petname
  - /petrelease
  - /petcst
  - /petskill
  - /petstop
  - /petinventory
  - /petpickup
  - /petbehavior
  - /msg
  - /r
  - /shop
  - /gps
  - /navi
  - /tagebuch
  - /skills
  - /akrobatik
  - /alchemie
  - /angeln
  - /axtkampf
  - /bergbau
  - /bogenschießen
  - /faustkampf
  - /graben
  - /holzfällen
  - /kräuterkunde
  - /reparatur
  - /schwert
  - /zähmen
  - /webseite
  - /homepage
  - /regelwerk
  - /karte
  - /socials
  - /info
  - /gemälde
  - /e

**Comment by motrellin** [comment]
@RobZenFL : Welche /grundstück-Commands gibt es alles?

**Comment by motrellin** [comment]
der Rest ist jetzt in einzelne Issues umgewandelt. fehlen nur noch die gs-commands

**Comment by motrellin** [comment]
scheint erledigt zu sein. Damit ist der Zweck dieser Issue erledigt.
