### ISSUE TITLE
[IMPROVEMENT] Add tutorials

### ISSUE THREAD

**Issue by RobZenFL** [FLBadoras/wiki#9]
### Grobbeschreibung

Übertrage Tutorials von Webseite.

### Beschreibung

Übertrage Tutorials von Webseite und freu dich nen Keks.

**Comment by motrellin** [comment]
Ich bin mir ehrlich gesagt unsicher, ob wir eine separate Sparte für Tutorials dieser Art brauchen. Praktisch ist sowas wie "Getränke" ja auch nur ein System. Und ich finde auch, dass die Unterscheidung vermutlich eher schwer wird auf Dauer. Deswegen würde ich das alles als System bezeichnen. Wie siehst du das?
