### ISSUE TITLE
Teamfarben

### ISSUE THREAD

**Issue by motrellin** [FLBadoras/wiki#90]
Kurze Frage mit Bezug zu #88 und #89 : Dort ist jetzt als Position "Architekt" bzw. "Scripter" eingetragen, also weder
- Serverleitung
- Moderation
- Support-Leitung
- Support
- Team

Das macht natürlich meine Farbtechnik kaputt. Ich hätte einen Lösungsvorschlag:
Wir ergänzen ein zusätzliches Tag, um Ränge einer Rangfarbe zuzuordnen. Bspw. könnten Architekt, Scripter etc. zu "Team" gehören, während Support und Support-Leitung zu "Support" gehören.

Eine andere Lösung wäre es, dass man in jedem Teammitgliedseintrag separat eine Farbe einträgt. Ist dann natürlich deutlich flexibler. 

Hast du eine Meinung dazu @RobZenFL ?

**Comment by RobZenFL** [comment]
Teamfarbe generell soll Orange sein. Dazu gehören alle Ränge außer Support und Leitung.

Warum ich hier doch genauere Ränge angebe: Da das Wiki ja mehr deep into Thema ist, würde ich da schon genauere Ränge definieren (wie Architekt), während ich sonst in der Außendarstellung eher allgemein bleibe (also "Team" - siehe Ingame und Discord). Sonst bräuchte man keine genaueren Wikieinträge, dann reicht eine Teamliste ohne Einzeleinträge für die Leute.

**Comment by motrellin** [comment]
> Teamfarbe generell soll Orange sein. Dazu gehören alle Ränge außer Support und Leitung.

Zwei Nachfragen da noch:

1. Soll das dann auch das Farbschema im Wiki sein?
2. War Moderation auch separat oder ist das auch orange?
